### ISSUE TITLE
先运行cnn，然后cnn-svm的结果0.29，可能是什么情况？

### ISSUE THREAD

**Issue by sxhfut** [wepe/MachineLearning#2]
12000/12000 [==============================] - 11s    
 Origin_model Accuracy: 0.964333333333
Start training SVM...
cnn-svm Accuracy: 0.299333333333
Start training Random Forest...
cnn-rf Accuracy: 0.295833333333

Process finished with exit code 0

**Comment by wepe** [comment]
我的demo不太严谨，加载完数据后，先打乱一下：

    import random
    index = [i for i in range(len(data))]
    random.shuffle(index)
    data = data[index]
    label = label[index]

你试试这样改后，结果怎么样？

**Comment by sxhfut** [comment]
多谢，试试在反馈

**Comment by sxhfut** [comment]
解决了，多谢！是不是因为存储下来data中的数据按照类别排序的？还是别的原因？

**Comment by wepe** [comment]
有可能是这原因，我读入数据的时候，样本就是乱的，可能你的机子就是按类别顺序读入。
