### ISSUE TITLE
CNN.py 不能运行

### ISSUE THREAD

**Issue by WERush** [wepe/MachineLearning#7]
CPU运行CNN.py时，出现

>TypeError: max_pool_2d() got an unexpected keyword argument 'mode' 

请问你有这种情况吗

**Comment by wepe** [comment]
可能是Theano版本太旧了，更新一下：
```
pip install --upgrade git+git://github.com/Theano/Theano.git
```

如果太慢，就直接下载下来，然后sudo python  setup.py install

**Comment by WERush** [comment]
https://github.com/wepe/MachineLearning/blob/master/DeepLearning%20Tutorials/keras_usage/cnn.py
这个文件运行报错
我更新了theano
>pip install --upgrade --no-deps theano 用这个命令

然后得到的结果是：

>Requirement already up-to-date: theano in /anaconda/lib/python2.7/site-packages

然后运行后，就报这个错误，难道我更新theano有问题？
