### ISSUE TITLE
Kmeans算法有必要自己实现吗？

### ISSUE THREAD

**Issue by Michael728** [wepe/MachineLearning#9]
刚刚学python没多久，想请问一下，python不是有很多现成的聚类了吗，有必要自己写吗？新人，盼解答

**Comment by wepe** [comment]
- 知乎上有个类似的问题，你可以看看。如果你对算法细节非常清楚，并且coding能力还行，那就实现一遍，花不了多少时间，实现算法的过程你能更深入地了解算法。
- Python，C++，Java，都有很多很好用的库，实际应用的时候一般直接用现成库。
